### ISSUE TITLE
[Bug] 紫外线灯会因为雪的覆盖而丢失

### ISSUE THREAD

**Issue by wumengzhixing** [Viola-Siemens/Survive-in-the-Winter-Frontier#1]
<img width="851" alt="41b411968c4f2c82e5cd6be3573ad685" src="https://github.com/Viola-Siemens/Survive-in-the-Winter-Frontier/assets/88496786/017006e4-e5d3-4f9b-a21c-f16436d93cef">

**Comment by Viola-Siemens** [comment]
Unable to reproduce, thinking that this may cause by some other mods. Any further information can be provided?
![image](https://github.com/Viola-Siemens/Survive-in-the-Winter-Frontier/assets/31766783/49a41dc9-a949-468f-9acb-8c33beeba836)
![image](https://github.com/Viola-Siemens/Survive-in-the-Winter-Frontier/assets/31766783/096571b3-230a-4a4d-8518-2fd4a797b301)
